### ISSUE TITLE
updating  DisplayName and PackageName in config.xml

### ISSUE THREAD

**Issue by mrvamsidhar** [SamVerschueren/cordova-config#15]
Hello, Thanks for providing this module. Really easy and Help ful.
One thing I like to know - is there any way to update DisplayName/Package Name?
The reason I am asking is, I need to provide different apks apks for different environments like DE, PROD etc. while build apk I need to update DisplayName and PackageName to differentiate between environments. Any way we can achieve this?

Thanks again

**Comment by SamVerschueren** [comment]
What tag is that? There is a [`setName`](https://github.com/SamVerschueren/cordova-config#setnamename) method. Not entirely sure if that would do for your use case?

**Comment by mrvamsidhar** [comment]
Looks like setID and setName resolves my issue. Thanks.

**Comment by SamVerschueren** [comment]
:+1: 

If you need additional methods, PR more then welcome ;)
